### ISSUE TITLE
Your mood is undefined on sunday

### ISSUE THREAD

**Issue by Ngopimas** [Melvynx/Melvynx#4]
Every sunday, your mood is `undefined`.

```JavaScript
// index.js

const today = new Date();

const moodByDay = {
  1: 'hate',
  2: 'wickedness',
  3: 'pleasure',
  4: 'wickedness',
  5: 'cruelty',
  6: 'horror',
  7: 'love',
};

function getGabotSigning() {
  const mood = moodByDay[today.getDay()];
  return `🤖 This README.md is updated with ${mood}, by Gabot ❤️`;
}
```

The [getDay()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/getDay) method of [Date](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date) instances returns the day of the week for this date according to local time, where 0 represents Sunday.

You might want to update the `7` key to `0` in the `moodByDay` object or update the `getGabotSigning` fn:
```JavaScript
// index.js

function getGabotSigning() {
  const mood = moodByDay[today.getDay() + 1]; // add `+ 1` to be in the 1-7 range
  return `🤖 This README.md is updated with ${mood}, by Gabot ❤️`;
}
```

Thank you for your work 🙏

**Comment by Melvynx** [comment]
Hi ! 

Thanks you, I made your change : https://github.com/Melvynx/Melvynx/commit/66960e4b374f2a102344bcdcdb79ed8664737fdd
